### ISSUE TITLE
Can you provide the MetaWorld version used in CARE?

### ISSUE THREAD

**Issue by NagisaZj** [facebookresearch/mtrl#11]
Hi @shagunsodhani ! As mentioned in #10 , Meta-World is under activate development, so it would be great if you can provide the version of Meta-World used in the CARE paper. Maybe you can specify which commit of Meta-World you used?

**Comment by shagunsodhani** [comment]
We use the `af8417bfc82a3e249b4b02156518d775f29eb289` commit for the MetaWorld environments for our experiments.

Fixed in https://github.com/facebookresearch/mtrl/commit/0b991a1bdfa7894f8807011616c5f0aeb7cc2407

**Comment by Amanda2024** [comment]
While installing the metaworld, I use:
`pip install git+https://hub.fastgit.org/facebookresearch/mtenv.git@main#egg="mtenv[metaworld_af8417bfc82a3e249b4b02156518d775f29eb289]"`

but there is always the error:

`hydra.errors.HydraException: Error calling 'mtrl.experiment.metaworld.Experiment' : Error calling 'metaworld.MT10' : Error loading module 'metaworld.MT10'`

**Comment by Amanda2024** [comment]
how can I fix it?

**Comment by JosselinSomervilleRoberts** [comment]
Hi @Amanda-1997 , were you able to fix it?
