### ISSUE TITLE
Run the code in the shell, but not work in the pycharm 

### ISSUE THREAD

**Issue by Amanda2024** [facebookresearch/mtrl#14]
# Description

I can run this code in the shell command, 

but with the same remote settings and Conda environment in the Pycharm,  it always occurs:

`raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.experiment.metaworld.Experiment' : Error calling 'metaworld.MT10' : Error loading module 'metaworld.MT10'`

## How to reproduce

```
python main.py setup=metaworld env=metaworld-mt10 agent=state_sac experiment.num_eval_episodes=1 experiment.num_train_steps=2000000 setup.seed=1 replay_buffer.batch_size=1280 agent.multitask.num_envs=10 agent.multitask.should_use_disentangled_alpha=True agent.multitask.should_use_task_encoder=True agent.encoder.type_to_select=film agent.multitask.should_use_multi_head_policy=False agent.multitask.task_encoder_cfg.model_cfg.pretrained_embedding_cfg.should_use=True agent.multitask.task_encoder_cfg.model_cfg.output_dim=6
```

## System information
- **MTRL Version** :  1
- **Python version** : 3.6.13

**Comment by shagunsodhani** [comment]
Hey @Amanda-1997 Thanks for your question. The issue might be because of some configuration issues with your PyCharm setup. I am not much familiar with PyCharm. Feel free to (re)-open the issue if you have any other questions.

**Comment by JosselinSomervilleRoberts** [comment]
Hi @Amanda-1997 I have the same error in VSCode, where you able to fix your problem? Thanks!
