### ISSUE TITLE
Multi-task SAC implementation

### ISSUE THREAD

**Issue by metaqiang** [facebookresearch/mtrl#15]
Multi-task SAC doesn't seem to concatenate one-hot task id into state.

**Comment by shagunsodhani** [comment]
Hi @yuyuanq Thanks for your question. You are correct, `Multi-task SAC` does not concatenate one-hot task id into state.. Maybe you are looking for `Multi-task SAC with task encoder?`

**Comment by metaqiang** [comment]
Thank you very much!
