### ISSUE TITLE
How to evaluate the trained model 

### ISSUE THREAD

**Issue by potato23333** [facebookresearch/mtrl#9]

**Comment by morgen-star** [comment]
The same question. How to evaluate the trained model....Is there any test script?

**Comment by shagunsodhani** [comment]
Hey @potato23333 @morgen-star ! Thank you for your question. I apologize for the late reply. There is no specific script for running the eval log. However, the function for evaluation is stand-alone and can be easily copy-pasted/imported in a standalone script. [Code 1](https://github.com/facebookresearch/mtrl/blob/184c7d39db21acc505cf7094ed87cd28a1735105/mtrl/experiment/dmcontrol.py#L33) and [Code 2](https://github.com/facebookresearch/mtrl/blob/184c7d39db21acc505cf7094ed87cd28a1735105/mtrl/experiment/metaworld.py#L81)

Let me know if this unblocks you. I have put this as a potential item to work as part of future iterations.
